### PR TITLE
Update to use jupyter-js-ui

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by dwillmer** [comment]
:+1:

**Comment by jasongrout** [comment]
It looks like you took the theming css and put it in jupyter-js-ui. That's going to make theming harder, right? Shouldn't the css that deals with visual style stay at the top-level so it's easy to swap out with a different theme?

**Comment by blink1073** [comment]
You just have to include the appropriate css at whatever level you choose.  Here, we're aggregating lower-level css in default-theme, and then using that from within the application.  You can mix and match at either layer.

**Comment by jasongrout** [comment]
ah. I didn't see that the application was still the thing pulling in the css. This simplifies things, thanks.

**Pull request merged**
