### PR TITLE
Fix new notebook kernel handling

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
cc @jasongrout, this is still a valid way to handle this even if we separate notebook creation from the file browser, and has the bonus of working now ;)

**Comment by jasongrout** [comment]
That's always a nice bonus!

**Comment by jasongrout** [comment]
As a favor, could you split the kernel stuff from the rendermime stuff in your first commit? I think that will make it much easier for me to rebase my current working branch on top of this. You can use http://gitup.co/ if you're on a mac to easily split the commit.

**Comment by blink1073** [comment]
Done.

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
