### PR TITLE
Tweaking shortcuts.

### PR DESCRIPTION
**Pull request by afshin**

### CODE REVIEW

**Comment by sccolbert** [comment]
I'm :-1: on the `Escape`-based shortcuts.

**Comment by jasongrout** [comment]
As much as I like emacs (and I really do love it), I'm with Chris on this one: -1 on escape-based shortcuts.

**Comment by Carreau** [comment]
This thing seem to need rebase.

**Comment by jasongrout** [comment]
Please reopen this against https://github.com/jupyter/jupyterlab if it is still applicable.

**Pull request closed without merging**
