### PR TITLE
Simplify resolvers

### PR DESCRIPTION
**Pull request by blink1073**
Also upgrade to phosphide 0.1 for the palette improvements.

### CODE REVIEW

**Comment by blink1073** [comment]
@jasongrout, this is the pattern we were looking for :)

**Comment by afshin** [comment]
Looks good to me.

**Comment by jasongrout** [comment]
I see how this pattern works.  I think it's a bit confusing because the `create` function is not actually creating anything, so I think I still prefer the other way, especially if resolve is changed to take a list.

Edit: See how the IFactory is supposed to return the thing it creates? https://github.com/phosphorjs/phosphor-di/blob/f2b48cb6c55efa70ef4c797bbfdab94c639ba908/src/index.ts#L81

**Comment by blink1073** [comment]
Yeah, I'll update so we're actually creating things.  I still think this is a fine pattern.

**Pull request merged**
