### PR TITLE
Add a provider which gives the currently focused notebook widget

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by jasongrout** [comment]
This looks all right for now.

**Comment by ellisonbg** [comment]
I will play with this now...

**Comment by ellisonbg** [comment]
Here is a plugin that uses this..

https://github.com/ellisonbg/jupyter-js-plugins/tree/active-notebook-kernel

**Comment by blink1073** [comment]
I sent a PR against yours.

**Comment by blink1073** [comment]
Updated.

**Comment by ellisonbg** [comment]
I haven't tested the signal, but everything else works perfectly. Merge if you want.

**Comment by ellisonbg** [comment]
Merging...

**Pull request merged**
