### PR TITLE
Add stub for about plugin

### PR DESCRIPTION
**Pull request by blink1073**
screen shot 2016-03-02 at 12 48 49 pm

### CODE REVIEW

**Comment by jasongrout** [comment]
Cool!

**Comment by rgbkrk** [comment]
Nice! Would one have to update the plugin directly here or would we be able to change the text over on the notebook side?

**Comment by blink1073** [comment]
The running theory has been that the notebook repo will essentially become a server only, with just the bootstrapping code.

**Comment by rgbkrk** [comment]
I mean to say that following on with a PR for "About" text - does it belong here or when integrated into the notebook?

**Comment by blink1073** [comment]
I meant everything should be here, the notebook side only assembles plugins, it does not contribute any.

**Pull request merged**
