### PR TITLE
Add a launcher

### PR DESCRIPTION
**Pull request by blink1073**
launcher

screen shot 2016-04-25 at 2 57 25 pm

cc @cameronoelsen @sccolbert

### CODE REVIEW

**Comment by cameronoelsen** [comment]
@blink1073 Is it possible to have the launcher not in a window but in just the main area when nothing is open?

**Comment by sccolbert** [comment]
This is possible, but we'll need to expose it in Phosphide. Can we leave that as a TODO until the phosphor repo merge is done?

**Comment by blink1073** [comment]
@cameronoelsen @sccolbert, I added #167 to track that.

**Comment by dwillmer** [comment]
LGTM

**Pull request merged**
