### PR TITLE
A first draft of an about page.

### PR DESCRIPTION
**Pull request by jasongrout**

### CODE REVIEW

**Comment by willingc** [comment]
@jasongrout A few wording suggestions... Overall, looks good.

**Comment by jasongrout** [comment]
@willingc - thanks! I think applied all your fixes.

**Comment by willingc** [comment]
@jasongrout Looks good to me. I'll let one of the JS folks or you merge. :+1:

**Comment by blink1073** [comment]
Merging, thanks!  I'll cut a release and make the necessary PR against `jupyter/notebook` tomorrow morning.

**Pull request merged**
