### PR TITLE
Basic Notebook Execution

### PR DESCRIPTION
**Pull request by blink1073**
Supersedes #32.

### CODE REVIEW

**Comment by blink1073** [comment]
@jasongrout, I rebased your PR and it is working now.

**Comment by jasongrout** [comment]
Can you delete all the Untitled files in the example directory?

**Comment by jasongrout** [comment]
Where did the widgetmanager.ts file go?

**Comment by jasongrout** [comment]
There are some other missing things here too.  I'm not sure what happened in the rebasing, but some changes are missing and others are added (like the new example files).

**Comment by blink1073** [comment]
On it.

**Comment by jasongrout** [comment]
I think I incorporated the necessary changes back into the original PR: #32.  It's probably easier to merge that at this point.

**Comment by blink1073** [comment]
Closing in favor of #32.

**Pull request closed without merging**
